export default Object.freeze({
  ADD_DEFAULT_PARAM: 'ADD_DEFAULT_PARAM',
  REMOVE_PARAM: 'REMOVE_PARAM',
  NAVIGATE_TO: 'NAVIGATE_TO',
  RESTORE_LOCATION: 'RESTORE_LOCATION',
  LOCATION_HASH: 'LOCATION_HASH',
  LOCATION_HISTORY: 'LOCATION_HISTORY'
});
